### ISSUE TITLE
Please update

### ISSUE THREAD

**Issue by rstrouse** [gadget-monk/homebridge-poolcontroller#10]
@gadget-monk can I get you to change the code so that the upnp device type no longer uses the upnp schemas for njspc.

The correct schema is `urn:schemas-tagyoureit-org:device:PoolController:1`.

In index.js lines 94, 103, and 108 change the text from `urn:schemas-upnp-org:device:PoolController:1` to `urn:schemas-tagyoureit-org:device:PoolController:1`

**Comment by gadget-monk** [comment]
done, thanks!
