### ISSUE TITLE
Version of poolController 1.0 does not meet the minimum for this Homebridge plugin 6.0

### ISSUE THREAD

**Issue by racerx9146** [gadget-monk/homebridge-poolcontroller#11]
Only works with SSDP on, with IP/URL i get 404 error. With SSDP (*) I get this 

[5/28/2022, 2:39:53 PM] [PoolControllerPlatform] Version of poolController 1.0 does not meet the minimum for this Homebridge plugin 6.0

**Comment by racerx9146** [comment]
this is the log when I put * in for the connection

6/2/2022, 11:29:56 AM] Living Room TV 834C is running on port 54408.
[6/2/2022, 11:29:56 AM] Please add [Living Room TV 834C] manually in Home app. Setup Code: 104-63-965
[6/2/2022, 11:29:56 AM] [PoolControllerPlatform] Version of poolController 1.0 does not meet the minimum for this Homebridge plugin 6.0
[6/2/2022, 11:29:56 AM] [HB Supervisor] Homebridge Process Ended. Code: 0, Signal: null
[6/2/2022, 11:30:01 AM] [HB Supervisor] Restarting Homebridge...

**Comment by kurtifier** [comment]
I am getting the same error as you. is there an update to fix it?

**Comment by racerx9146** [comment]
No I rather think this has been abandoned. I spent quite a bit of time searching for it. Would love to see it work.

**Comment by kurtifier** [comment]
Has anyone had any success in getting homekit to work?

**Comment by dkossman** [comment]
@kurtifier I had this plugin working reasonably well with an older version of poolController - I think it was around 6.1 but its been a while so I could be wrong.  My Pi running poolController died, I replaced it, and I've not had time to try to resurrect things.

**Comment by racerx9146** [comment]
I am still interested in getting this working.  Would be great to have some basic functionality in HomeKit like turn the Spa on on my way home :) I did see somebody else working on it it here https://github.com/michaelmedellin/homebridge-poolcontroller#readme

**Comment by rstrouse** [comment]
See this discussion and pull the latest njsPC.  The specVersion was previously being used for upnp discovery.  This is the upnp architecture version and should not be used to determine the version of njsPC.

https://github.com/tagyoureit/nodejs-poolController/discussions/597

Lines 127 & 128 of index.js should read as follows.

```
        var major = parseInt(body.match(/<device>[\s|\S]+<appVersion>[\s|\S]+<major>(\d+)<\/major>/)[1], 10);
        var minor = parseInt(body.match(/<device>[\s|\S]+<appVersion>[\s|\S]+<minor>(\d+)<\/minor>/)[1], 10);
```

**Comment by kurtifier** [comment]
@rstrouse thank you for the link. Gadget-monk just posted and update and it worked for me!@racerx9146 @dkossman. Thank you @gadget-monk!
