### ISSUE TITLE
Screenshots?

### ISSUE THREAD

**Issue by ccorcos** [gadget-monk/homebridge-poolcontroller#14]
It would be nice to see what this looks like in HomeKit before committing to trying this out...

Thanks! 😄

**Comment by spifftek70** [comment]
<img width="764" alt="Screenshot 2022-12-24 at 7 40 14 AM" src="https://user-images.githubusercontent.com/11727190/209440838-a361c9e7-3578-4810-a1d5-f82b931121e8.png">
<img width="925" alt="Screenshot 2022-12-24 at 7 40 05 AM" src="https://user-images.githubusercontent.com/11727190/209440839-968b8790-5cef-41e2-b04a-ed7cb59c094e.png">

**Comment by spifftek70** [comment]
Here's how it looks.  `Other` are `circuits` from the `NodeJS PoolController`

**Comment by ccorcos** [comment]
Awesome. Thanks for that! So my pool has a single heater with a valve that switches between heating the pool vs the spa. So I'm assuming the "Spa" mode will just be one of those "Other" circuits? I've got an EasyTouch system... Just wondering if you know, otherwise, I'll just have to figure it out!

Thanks, 

Chet
